### ISSUE TITLE
Psycho Gigacyber placing a Pendulum monster as Continuous Trap

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#270] opened 2020-06-03 09:42 UTC
If `Psycho Gigacyber` places a Pendulum Monster in the S/T Zone as a Continuous Trap, in sequences 0  or 4, that Pendulum Monster is treated as being a Pendulum Scale rather than a Continuous Trap.

Test puzzle:
```lua
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_TEST_MODE,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

--Hand
Debug.AddCard(31222701,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(69982329,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(21844576,0,0,LOCATION_HAND,0,POS_FACEDOWN)
--Monster Zones
Debug.AddCard(91870448,0,0,LOCATION_MZONE,0,1,true)
Debug.AddCard(77585513,0,0,LOCATION_MZONE,1,1,true)
--Hand
Debug.AddCard(49684352,1,1,LOCATION_HAND,0,POS_FACEDOWN)
--Monster Zones
Debug.AddCard(48461764,1,1,LOCATION_MZONE,3,4,true)
Debug.AddCard(79979666,1,1,LOCATION_MZONE,1,4,true)
--Spell & Trap Zones
Debug.AddCard(49684352,1,1,LOCATION_PZONE,0,5)
Debug.AddCard(42378577,1,1,LOCATION_SZONE,2,5)
Debug.ReloadFieldEnd()
```

**Comment by ahtelel** [comment] 2020-06-16 09:38
Personal testing gives:
The Pendulum Monster placed by `Psycho Gigacyber`'s effect will be a scale in any sequence of the S/T Zone. Maybe the problem is how the core treats Pendulum Monsters in the S/T Zone in general?

**Comment by edo9300** [comment] 2020-06-16 10:28
This interaction has been fixed in https://github.com/edo9300/ygopro-core/commit/b5020dd3cf17b7f7ec1e6d472c3d34ad66200412

**Closed by edo9300** 2020-06-16 10:28 UTC
Labels: bug
